using System;
using System.Collections.Generic;
using System.Text;

namespace pp2maplist
{
    class Program
    {
        public static List<Lake> lakes = new List<Lake>();
        static void Main(string[] args)
        {
            Console.WriteLine("********************************************************");
            Console.WriteLine("ProPilkki2 Maplist Generator By Topias Mariapori");
            Console.WriteLine("************************v.0.1 BETA****************************");
            Console.WriteLine("How many lakes?");
            int lakesCount = Convert.ToInt32(Console.ReadLine());
            for (int i = 0; i < lakesCount; i++)
            {
                Lake uusi = new Lake();
                Console.WriteLine("Lakes");
                Console.WriteLine("Haapolahti");
                Console.WriteLine("Haukilahti");
                Console.WriteLine("Hossalaislammet");
                Console.WriteLine("Iso-Ruuhijärvi");
                Console.WriteLine("Iso-Söimi");
                Console.WriteLine("Jormuanlahti");
                Console.WriteLine("Kivijoki");
                Console.WriteLine("Koivusaarenmatalikko");
                Console.WriteLine("Kolmisoppi");
                Console.WriteLine("Korpipuro");
                Console.WriteLine("Kortejärvi");
                Console.WriteLine("Kuikansalmi");
                Console.WriteLine("Kuopionlahti");
                Console.WriteLine("Lahnalammet");
                Console.WriteLine("Lehmilampi");
                Console.WriteLine("Linlonlahti");
                Console.WriteLine("Lokkiluoto");
                Console.WriteLine("Meri");
                Console.WriteLine("Metsälampi");
                Console.WriteLine("Muddusjärvi");
                Console.WriteLine("Mustalampi");
                Console.WriteLine("Mäntylahti");
                Console.WriteLine("Niemisjärvet");
                Console.WriteLine("PieniSärkinen");
                Console.WriteLine("Pitkälampi");
                Console.WriteLine("Pohjalampi");
                Console.WriteLine("Rautupuro");
                Console.WriteLine("Saarijärvi");
                Console.WriteLine("Savilahti");
                Console.WriteLine("Siika-Valkeinen");
                Console.WriteLine("Siikakoski");
                Console.WriteLine("Surrinlampi");
                Console.WriteLine("Särkijärvi");
                Console.WriteLine("Taivallampi");
                Console.WriteLine("Telkänlampi");
                Console.WriteLine("Ullavanjärvi");
                Console.WriteLine("Venetjoentekojärvi");
                Console.WriteLine("Viitalampi");
                Console.WriteLine("Vuolasniva");
                Console.WriteLine("Vuontele");
                Console.WriteLine("Räväjärvi");
                Console.WriteLine("Lake: ");
                uusi.lakeName = Console.ReadLine();
                Console.WriteLine("Game time:");
                Console.WriteLine("(1 = 10 min, 2 = 15 min, 3 = 30 min, 4 = 60 min, 5 = 90 min ja 6 = 120 min)");
                uusi.gameTime = Console.ReadLine();
                Console.WriteLine("Game mode:");
                Console.WriteLine("(1 = Normal)");
                uusi.gameMode = Console.ReadLine();
                lakes.Add(uusi);
                Console.Clear();
            }
            List<string> sb = new List<string>();
            sb.Add("# This file is generated by pp2maplist");
            sb.Add("/autohost on");
            sb.Add("/lures all");
            sb.Add("/wait 15");
            sb.Add("/results 8");
            foreach (var lake in lakes)
            {
                sb.Add("###################");
                sb.Add("/lake " + lake.lakeName + "," + lake.gameTime);
                sb.Add("/game " + lake.gameMode);
                sb.Add("###################");
            }
            sb.Add("/autoscript  on");

            System.IO.File.WriteAllLines("autoscript.txt", sb);
            Console.WriteLine("File created! Press any key to exit program..");
            Console.ReadKey();
        }
    }
}
